apiVersion: v1
kind: Service
metadata:
  name: {{ include "holmes-sre.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "holmes-sre.labels" . | nindent 4 }}
  {{- if and (eq .Values.investigator.service.type "LoadBalancer") .Values.investigator.service.dnsLabel }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.investigator.service.dnsLabel | quote }}
  {{- end }}
spec:
  type: {{ .Values.investigator.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "holmes-sre.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.investigator.service.port }}
      targetPort: 8000
